services:
  db:
    image: postgres:15
    container_name: walk-chat-db
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "walk-user", "-d", "walk-chat" ]
      interval: 3s
      timeout: 1s
      retries: 1
    volumes:
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  walk-profile:
    build:
      context: .
    container_name: walk-chat-app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    command: ["/walk-chat/docker/app.sh"]
    ports:
      - 8002:8000
